### PR TITLE
Fix for ICH10R ACPI chipset

### PR DESCRIPTION
**Pull request by 123marvin123**
Hello,

got another fix today for the ICH10R ACPI chipset which I found on [tonymacx86.com](https://www.tonymacx86.com/threads/solved-ich10r-and-high-sierra.233435/page-2#post-1608408). This patch is necessary to make my Caddy Bay work (I replaced the DVD drive with a hard drive).

Caddy Bay

### CODE REVIEW

**Comment by drasbeck** [comment]
Hi @123marvin123, what is fixed with the ICH10R ACPI chipset? Also what was the problem with the caddy? I've been using a caddy as long as I've had my T430, never had to do anything for it to work in any environment (Hackintosh, Windows, Linux, BIOS).

I am quite busy right now, and need a stable Hack. Thus I cannot test your patch at this moment.

**Comment by 123marvin123** [comment]
It was recognizing the name of the hard drive and the size, but not the partition scheme and I also couldn't format it. The caddy was working fine with windows and linux, but not with macOS. I was getting "I/o error" in the logs and I found the ICH10R patch which seems to be quite common and it immediately fixed the problem.

Which combination are you using with your caddy bay? I'm using a normal hdd instead of an SSD in the caddy bay, maybe that's the issue? Could you activate the "Issues" tab on this GitHub project or provide a possibility to communicate? I have a few small issues with my setup and I would like to talk to somebody that uses a T430 Hackintosh too.

Maybe I can add the ICH10R patch as an optional notice into the README file and remove it from the config.plist file.

**Comment by drasbeck** [comment]
Issues tab has been activated, my bad. =)

And my setup is a secondary SSD connected via the caddy bay and a primary connected via the drive bay. What is your setup, and what is your macOS version?

**Comment by 123marvin123** [comment]
I bought a refurbished t430 and took the main hdd out and replaced it with a Toshiba SSD and put the "old" hdd (which is still quite fast) into the caddy bay. It was working fine on Windows and Linux but it gave me issues on macOS (I almost gave up, but it's working fine now with 100 mb/s speed using the patch).

I'm on the latest Mojave 10.14.3 and looking to upgrade to an i7 for quad-core and I also bought a new screen (the HD+ one) but still waiting for the cable from china. 16gb ram working great, but I am having minor issues with the sound setup. Is your in-built microphone working? I just can't get it to work, and the webcam is super dark, not sure if this is normal (haven't tried on windows). I can get the microphone to work with VoodooHDA, but the voodoo audio driver is quite shitty 👎🏻.

**Comment by drasbeck** [comment]
I really want to merge your PR with the master branch, and again thank you so much for contributing. But I really need to test it first, to see if it (for any reason) breaks my own caddy support. Hope you can appreciate that.

My internal mic works, it's just turned way down. When I tap on the T430 chassis the mic registers it (as seen in System Preferences->Sound->Input (choose Internal Microphone and tap away)), but speech is not registering. I don't know why it's turned down, and haven't looked into it, since I use an external sound card (SoundBlaster E5) which works flawlessly. I suggest submitting an issue with regards to the mic if you'd like. Hopefully somebody will pick it up.

GL with the HD+ display. I installed a FHD and it made the computer so much better. It resulted in breaking the output to DisplayPort though. Hmm, maybe _I_ should also submit a couple of issues. 🤔

**Comment by 123marvin123** [comment]
Would you mind uploading your config.plist here? I followed the README guide when installing macOS, I copied the kexts from the kexts folder to Kext Utility. Did you do anything different than what is described in the README file? A list of your installed kexts would be nice too.

**Comment by drasbeck** [comment]
I have followed the guide (back in the day) and since then made the updates as seen in [update_log.md](https://github.com/drasbeck/macos-thinkpad-t430/blob/master/update_log.md). My config.plist is identical to the high res one, except for anything related to S/N.

I will at some point make a page that gives an overview of my current clover setup. Until then here's a list of my installed kexts. Hope it helps.

```
❯ ll /Volumes/EFI/EFI/CLOVER/kexts/Other/
total 16
drwxrwxrwx  1 max  staff   512B Sep 19 21:52 ACPIBatteryManager.kext
drwxrwxrwx  1 max  staff   512B Feb  5 10:13 AppleALC.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 AppleBacklight.kext
drwxrwxrwx  1 max  staff   512B Sep 19 11:57 BrcmBluetoothInjector.kext
drwxrwxrwx  1 max  staff   512B Jun  4  2018 BrcmFirmwareRepo.kext
drwxrwxrwx  1 max  staff   512B Jun  4  2018 BrcmPatchRAM2.kext
drwxrwxrwx@ 1 max  staff   512B Oct  3 14:49 CodecCommander.kext
drwxrwxrwx  1 max  staff   512B Sep 15 11:04 FakeSMC.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_ACPISensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_CPUSensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_GPUSensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_LPCSensors.kext
drwxrwxrwx  1 max  staff   512B Apr 24  2018 IntelMausiEthernet.kext
drwxrwxrwx  1 max  staff   512B Feb  5 10:06 Lilu.kext
drwxrwxrwx  1 max  staff   512B Oct 29  2017 VoodooPS2Controller.kext
drwxrwxrwx  1 max  staff   512B Sep 19 12:58 toledaARPT.kext

~
❯
```

**Comment by drasbeck** [comment]
```
❯ ll /Volumes/EFI/EFI/CLOVER/kexts/Other/
total 16
drwxrwxrwx  1 max  staff   512B Sep 19 21:52 ACPIBatteryManager.kext
drwxrwxrwx  1 max  staff   512B Feb  5 10:13 AppleALC.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 AppleBacklight.kext
drwxrwxrwx  1 max  staff   512B Sep 19 11:57 BrcmBluetoothInjector.kext
drwxrwxrwx  1 max  staff   512B Jun  4  2018 BrcmFirmwareRepo.kext
drwxrwxrwx  1 max  staff   512B Jun  4  2018 BrcmPatchRAM2.kext
drwxrwxrwx@ 1 max  staff   512B Oct  3 14:49 CodecCommander.kext
drwxrwxrwx  1 max  staff   512B Sep 15 11:04 FakeSMC.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_ACPISensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_CPUSensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_GPUSensors.kext
drwxrwxrwx  1 max  staff   512B Nov 19  2017 FakeSMC_LPCSensors.kext
drwxrwxrwx  1 max  staff   512B Apr 24  2018 IntelMausiEthernet.kext
drwxrwxrwx  1 max  staff   512B Feb  5 10:06 Lilu.kext
drwxrwxrwx  1 max  staff   512B Oct 29  2017 VoodooPS2Controller.kext
drwxrwxrwx  1 max  staff   512B Sep 19 12:58 toledaARPT.kext

~
❯
```

**Comment by 123marvin123** [comment]
Thanks for the config.plist and kext info. I moved my kexts from /S/L/E to the clover kext folder and made some progress. I only got static noise and something when tapping on the chassis, but could hear me voice at all.

I fixed the issue by switching to layout-id 29, please see my fix in PR #10 (Siri is now working too).

**Comment by drasbeck** [comment]
@123marvin123 are you on the Hackintosh Discord? We could communicate through that.

**Comment by 123marvin123** [comment]
I registered on this server: https://discordapp.com/invite/u8V7N5C

How to communicate there? My username is 123marvin123

**Comment by 123marvin123** [comment]
This PR has been polluted due to bad branch management on my side 😬 I will close it and will make a clean one.

**Pull request closed without merging**
